version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    env_file:
      - ./docker/development/.env
      - ./docker/development/.env.db
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app:z
    ports:
      - "8000:8000"
  postgres:
    image: postgres:14-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=social_media
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.8-bullseye
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: