[tool.ruff]
line-length = 79
select = ["E", "F", "I"]

[tool.ruff.per-file-ignores]
"app/db_models/__init__.py" = ["F401"]

[[tool.mypy.overrides]]
module = [
  "app.*"
]
ignore_missing_imports = true
follow_imports = "normal"
disallow_untyped_defs = true
disallow_untyped_calls = true

[[tool.mypy.overrides]]
module = [
  "app.tests.*"
]
ignore_errors = true

[[tool.mypy.overrides]]
module = [
    "sqlalchemy.*",
    "uvicorn.*",
]
disallow_untyped_calls = false
ignore_missing_imports = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
testpaths = [
  "app"
]
addopts = "-v -rsxX -l --tb=short --strict -p no:warnings"
xfails_strict = true
markers = [
  "tmp: Temporary",
  "optional: Optional",
]
env = [
  "APP_CONFIG_FILE=test"
]