"""Add fullname, email, location, and company columns to users table

Revision ID: ab0f6a8e7db2
Revises: 2959403c03a5
Create Date: 2023-01-07 18:28:21.367423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0f6a8e7db2'
down_revision = '2959403c03a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company')
    op.drop_column('users', 'location')
    op.drop_column('users', 'email')
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###
